/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Client
 */
public class ClientTest {
    private final Client model = new Client();

    /**
     * Model tests for Client
     */
    @Test
    public void testClient() {
        // TODO: test Client
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'document'
     */
    @Test
    public void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'surname'
     */
    @Test
    public void surnameTest() {
        // TODO: test surname
    }

    /**
     * Test the property 'firstname'
     */
    @Test
    public void firstnameTest() {
        // TODO: test firstname
    }

    /**
     * Test the property 'patronymic'
     */
    @Test
    public void patronymicTest() {
        // TODO: test patronymic
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    public void birthdayTest() {
        // TODO: test birthday
    }

}
