/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Client;
import org.openapitools.client.model.ClientRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientControllerApi
 */
@Disabled
public class ClientControllerApiTest {

    private final ClientControllerApi api = new ClientControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void create2Test() throws ApiException {
        Integer clientId = null;
        ClientRequest clientRequest = null;
        Integer response = api.create2(clientId, clientRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void create5Test() throws ApiException {
        ClientRequest clientRequest = null;
        Integer response = api.create5(clientRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void delete2Test() throws ApiException {
        Integer clientId = null;
        Integer response = api.delete2(clientId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getById2Test() throws ApiException {
        Integer clientId = null;
        Client response = api.getById2(clientId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showAll2Test() throws ApiException {
        List<Client> response = api.showAll2();
        // TODO: test validations
    }

}
