/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Consultation;
import org.openapitools.client.model.ConsultationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConsultationControllerApi
 */
@Disabled
public class ConsultationControllerApiTest {

    private final ConsultationControllerApi api = new ConsultationControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void create1Test() throws ApiException {
        Integer consultationId = null;
        ConsultationRequest consultationRequest = null;
        Integer response = api.create1(consultationId, consultationRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void create4Test() throws ApiException {
        ConsultationRequest consultationRequest = null;
        Integer response = api.create4(consultationRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void delete1Test() throws ApiException {
        Integer consultationId = null;
        Integer response = api.delete1(consultationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getById1Test() throws ApiException {
        Integer consultationId = null;
        Consultation response = api.getById1(consultationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showAll1Test() throws ApiException {
        List<Consultation> response = api.showAll1();
        // TODO: test validations
    }

}
